FROM node:14.18.0-alpine AS installer

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

FROM node:14.18.0-alpine AS builder

WORKDIR /usr/src/app

COPY --from=installer /usr/src/app/node_modules /usr/src/app/node_modules

COPY . .

RUN npm run build

FROM node:14.18.0-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist /usr/src/app/dist

EXPOSE 3000

CMD ["node", "dist/main"]
